server {
    listen 80;
    server_name localhost;

    location /php/ {
        rewrite ^/php/(.*)$ /$1 break;
        fastcgi_pass php-fpm:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
        fastcgi_param PATH_INFO $uri;
    }

    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://nodejs-api:3000;
        proxy_set_header Host $host;                # !!!
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 10M;                   # !!!
    }

    location /files/ {
        alias /var/www/files/;
        autoindex off;                              # !!!
    }
}